"""Rebuild a decoder-side PC-HBM memory from a saved TS Student checkpoint.

The exported memory is generated by the exact Decoder/PC-HBM weights stored in
the checkpoint and carries their producer fingerprint.  Only the deterministic
labeled split is used; pseudo labels never enter the memory.
"""

from __future__ import annotations

import argparse
import sys
from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import Any

import torch


PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from configs.pc_hbm_dino_config import DinoPCHBMConfig
from configs.ts_model_config import Config
from Model.base_model import BaseModel
from Model.PC_HBM.memory import PCMemory
from utils.checkpoint_pc_hbm import (
    build_artifact_metadata,
    compute_labeled_split_fingerprint,
    load_decoder_compatible,
    load_memory_checkpoint,
    read_artifact_metadata,
    save_memory_checkpoint,
)
from utils.dataloader import build_labeled_memory_loader
from utils.pc_memory_runner import build_memory_compat_meta, rebuild_memory


def _torch_load(path: Path) -> Mapping[str, Any]:
    try:
        payload = torch.load(path, map_location="cpu", weights_only=False)
    except TypeError:
        payload = torch.load(path, map_location="cpu")
    if not isinstance(payload, Mapping):
        raise TypeError(f"Decoder checkpoint must be a mapping, got {type(payload).__name__}")
    return payload


def _restore_pc_config(checkpoint: Mapping[str, Any]) -> DinoPCHBMConfig:
    snapshot = checkpoint.get("pc_cfg")
    if not isinstance(snapshot, Mapping):
        raise RuntimeError(
            "Checkpoint has no pc_cfg mapping; an exact producer-compatible memory "
            "cannot be reconstructed safely."
        )
    restored = dict(snapshot)
    decoder_state = checkpoint.get("decoder")
    legacy_decoder = isinstance(decoder_state, Mapping) and any(
        str(key).startswith("TransBlock_seg") for key in decoder_state
    )
    legacy_schema = int(restored.get("memory_schema_version", 1)) == 1
    migrated_legacy = legacy_decoder and legacy_schema
    if migrated_legacy:
        # Pre-BGFBR checkpoints used the legacy Transformer decoder and the
        # original four boundary descriptors.  Recreate that exact module
        # shape, while exporting its newly rebuilt memory in schema v2 so the
        # current strict producer-fingerprint checks can validate it.
        restored.update(
            memory_schema_version=2,
            memory_architecture="DINO_SCOD_BGFBR_PC_HBM",
            decoder_arch="legacy_transformer",
            experiment_profile="legacy_pc_migrated",
        )
    try:
        config = DinoPCHBMConfig(**restored)
    except TypeError as error:
        raise RuntimeError(
            "Checkpoint pc_cfg is incompatible with the current DinoPCHBMConfig schema"
        ) from error
    if migrated_legacy:
        config.boundary_feature_channels = (5, 8, 8, 14)
        config.use_pc_boundary_context = False
        config.use_gbe = False
        config.use_ode = False
        config.use_rcab = False
        print(
            "Migrated legacy schema-v1 Decoder config: "
            "decoder_arch=legacy_transformer, "
            "boundary_feature_channels=(5, 8, 8, 14), export_schema=2"
        )
    if str(getattr(config, "pc_placement", "decoder")) != "decoder":
        raise ValueError("This utility only supports decoder-side PC-HBM checkpoints")
    return config


def _memory_artifact_metadata(
    decoder_artifact: Mapping[str, Any] | None,
) -> dict[str, Any] | None:
    if decoder_artifact is None:
        return None
    if decoder_artifact["artifact_role"] != "student_joint":
        raise ValueError(
            "Expected a joint TS Student artifact, got "
            f"artifact_role={decoder_artifact['artifact_role']!r}"
        )
    if decoder_artifact["training_design"] != "joint":
        raise ValueError(
            "Expected training_design='joint', got "
            f"{decoder_artifact['training_design']!r}"
        )
    return build_artifact_metadata(
        training_design=str(decoder_artifact["training_design"]),
        artifact_role="student_memory",
        labeled_split_fingerprint=str(
            decoder_artifact["labeled_split_fingerprint"]
        ),
        baseline_fingerprint=str(decoder_artifact["baseline_fingerprint"]),
        pc_frozen=bool(decoder_artifact["pc_frozen"]),
    )


def _new_memory(config: DinoPCHBMConfig) -> PCMemory:
    return PCMemory(
        memory_dim=int(config.memory_dim),
        value_dim=int(config.value_dim),
        geometry_dim=int(config.geometry_dim),
        storage_dtype=config.memory_storage_dtype,
        config=config,
    )


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Rebuild a strict producer-matched PC-HBM memory from a TS Student."
    )
    parser.add_argument("--decoder-checkpoint", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument(
        "--expected-epoch",
        type=int,
        default=None,
        help="Fail unless the checkpoint epoch equals this value (for example, 13).",
    )
    parser.add_argument(
        "--labeled-indices-pt",
        type=Path,
        default=None,
        help=(
            "The exact labeled split .pt used by training. Omit only when training "
            "used Config.train_sample_txt directly."
        ),
    )
    parser.add_argument("--batch-size", type=int, default=16)
    parser.add_argument("--num-workers", type=int, default=0)
    parser.add_argument("--device", default="cuda")
    parser.add_argument("--no-amp", action="store_true")
    parser.add_argument(
        "--allow-untagged",
        action="store_true",
        help=(
            "Allow a legacy checkpoint without artifact metadata. This disables "
            "labeled-split fingerprint verification."
        ),
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Allow replacing an existing output memory checkpoint.",
    )
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(argv)
    if Path.cwd().resolve() != PROJECT_ROOT:
        raise RuntimeError(f"Run this utility from the project root: {PROJECT_ROOT}")
    decoder_path = args.decoder_checkpoint.resolve()
    output_path = args.output.resolve()
    if not decoder_path.is_file():
        raise FileNotFoundError(f"Decoder checkpoint not found: {decoder_path}")
    if output_path == decoder_path:
        raise ValueError("--output must not overwrite --decoder-checkpoint")
    if output_path.exists() and not args.force:
        raise FileExistsError(
            f"Output already exists: {output_path}; pass --force to replace it"
        )
    if args.labeled_indices_pt is not None and not args.labeled_indices_pt.is_file():
        raise FileNotFoundError(
            f"Labeled split file not found: {args.labeled_indices_pt.resolve()}"
        )
    if args.batch_size <= 0:
        raise ValueError("--batch-size must be positive")
    if args.num_workers < 0:
        raise ValueError("--num-workers must be non-negative")

    checkpoint = _torch_load(decoder_path)
    checkpoint_epoch = checkpoint.get("epoch")
    if checkpoint_epoch is None:
        raise RuntimeError("Decoder checkpoint does not record its epoch")
    checkpoint_epoch = int(checkpoint_epoch)
    if args.expected_epoch is not None and checkpoint_epoch != args.expected_epoch:
        raise RuntimeError(
            f"Expected epoch {args.expected_epoch}, checkpoint records epoch {checkpoint_epoch}"
        )

    pc_cfg = _restore_pc_config(checkpoint)
    decoder_artifact = read_artifact_metadata(checkpoint)
    if decoder_artifact is None and not args.allow_untagged:
        raise RuntimeError(
            "Decoder checkpoint has no artifact metadata, so its labeled split "
            "cannot be verified. Use a current student_joint checkpoint or pass "
            "--allow-untagged only for a deliberate legacy reconstruction."
        )
    memory_artifact = _memory_artifact_metadata(decoder_artifact)

    train_cfg = Config()
    train_cfg.train_labeled_indices_pt = (
        None
        if args.labeled_indices_pt is None
        else str(args.labeled_indices_pt.resolve())
    )
    memory_loader = build_labeled_memory_loader(
        train_cfg.train_imgs,
        train_cfg.train_masks,
        train_cfg.train_sample_txt,
        train_cfg.l_train_size,
        labeled_indices_pt=train_cfg.train_labeled_indices_pt,
        batch_size=args.batch_size,
        num_workers=args.num_workers,
        pin_memory=str(args.device).startswith("cuda"),
    )
    split_fingerprint = compute_labeled_split_fingerprint(
        memory_loader.dataset.sample_keys
    )
    if decoder_artifact is not None:
        expected_split = str(decoder_artifact["labeled_split_fingerprint"])
        if split_fingerprint != expected_split:
            raise RuntimeError(
                "Labeled split fingerprint does not match the Student checkpoint. "
                "Pass the exact --labeled-indices-pt used by the original run. "
                f"expected={expected_split}, actual={split_fingerprint}"
            )

    device = torch.device(args.device)
    if device.type == "cuda" and not torch.cuda.is_available():
        raise RuntimeError("CUDA was requested but is unavailable")

    model = BaseModel(pc_cfg=pc_cfg, attach_pc=True)
    load_decoder_compatible(
        model.decoder,
        checkpoint,
        require_pc_complete=True,
    )
    model.to(device).eval()

    memory = _new_memory(pc_cfg)
    compat_meta = build_memory_compat_meta(
        pc_cfg,
        model.decoder,
        producer_source=f"student_epoch_{checkpoint_epoch}",
    )
    with torch.inference_mode():
        rebuild_memory(
            model=model,
            memory_decoder=model.decoder,
            memory_loader=memory_loader,
            memory=memory,
            device=device,
            config=pc_cfg,
            compat_meta=compat_meta,
            use_amp=not args.no_amp,
        )

    compatibility = memory.validate_compat(
        compat_meta,
        require_producer_match=True,
    )
    if not bool(compatibility):
        reason = getattr(compatibility, "reason", "unknown compatibility failure")
        raise RuntimeError(f"Rebuilt memory failed strict validation: {reason}")

    save_memory_checkpoint(
        output_path,
        memory,
        compat_meta=compat_meta,
        artifact_meta=memory_artifact,
    )
    round_trip_memory = _new_memory(pc_cfg)
    load_memory_checkpoint(
        output_path,
        round_trip_memory,
        expected_compat=compat_meta,
        require_producer_match=True,
    )
    print(f"Saved: {output_path}")
    print(f"Checkpoint epoch: {checkpoint_epoch}")
    print(f"Labeled samples: {len(memory_loader.dataset)}")
    print(f"Labeled split fingerprint: {split_fingerprint}")
    print(f"Producer fingerprint: {compat_meta['producer_fingerprint']}")
    print(memory.diagnostic_string())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
